version: '3.3'
services:
    app:
        build:
            dockerfile: Dockerfile
        ports:
            - '80:3000'
        volumes:
            - './.data:/app/.data'
        restart: always
        logging:
            options:
                max-size: 1g
