version: '3.3'
services:
    node:
        ports:
            - '80:3000'
        volumes:
            - '$PWD/.data:/app/.data'
        restart: always
        logging:
            options:
                max-size: 1g
        image: 'node:18-alpine'
